spring.application.name=tt-backend

spring.datasource.url=jdbc:mysql://localhost:3306/tortas_db
spring.datasource.username=root
spring.datasource.password=Hunter20#
spring.jpa.hibernate.ddl-auto=update